'use client'
import type { Metadata } from 'next'
import Layout from './layouts/Layout'
import StoreProvider from '@/app/StoreProvider'
import { ErrorBoundary } from '@/src/shared/lib/bugsnag'
import { QueryClient, QueryClientProvider } from 'react-query'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const queryClient = new QueryClient()

export function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <ErrorBoundary>
          <StoreProvider>
            <QueryClientProvider client={queryClient}>
              <Layout>{children}</Layout>
            </QueryClientProvider>
          </StoreProvider>
        </ErrorBoundary>
      </body>
    </html>
  )
}
