import type { Metadata } from 'next'
import Layout from './layouts/Layout'
import StoreProvider from '@/app/StoreProvider'
import { ErrorBoundary } from '@/src/shared/lib/bugsnag'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <ErrorBoundary>
          <StoreProvider>
            <Layout>{children}</Layout>
          </StoreProvider>
        </ErrorBoundary>
      </body>
    </html>
  )
}
