#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

export PATH="$PATH:/Users/vsevolod/.nvm/versions/node/v20.9.0/bin"  # Добавьте эту строку


echo "Current PATH: $PATH"

# Running Prettier and ESLint from package.json scripts
yarn prettier-format
yarn lint



# Automatically add changes to the staging area
git add .
